custom:
  bert_base_path: gpt_sovits/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: gpt_sovits/GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda
  is_half: true
  t2s_weights_path: gpt_sovits/GPT_weights/hu-tao-tts-v1.2-e15.ckpt
  vits_weights_path: gpt_sovits/SoVITS_weights/hu-tao-tts-v1.2_e12_s168.pth
default:
  bert_base_path: gpt_sovits/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: gpt_sovits/GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: gpt_sovits/GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
  vits_weights_path: gpt_sovits/GPT_SoVITS/pretrained_models/s2G488k.pth
